// ─────────────────────────────────────────────────────────────────────────────
// Fake AI Provider – deterministic stub for local dev / CI
// Set AI_PROVIDER=fake in .env.local to use this instead of a real LLM
// ─────────────────────────────────────────────────────────────────────────────

import type { MoMData } from "@/types";
import type { AIProvider } from "./interface";

const STUB: MoMData = {
  meeting_title: "Q2 Product Planning Meeting [DEMO]",
  meeting_date: "2024-04-10",
  meeting_time: "10:00 AM",
  location_or_platform: "Microsoft Teams",
  facilitator: "Sarah Johnson",
  attendees: [
    { name: "Sarah Johnson", role: "Product Manager", organization: "Acme Corp" },
    { name: "Mark Lee", role: "Engineering Lead", organization: "Acme Corp" },
    { name: "Priya Shah", role: "Designer", organization: "Acme Corp" },
    { name: "Tom Nguyen", role: "QA Lead", organization: "Acme Corp" },
  ],
  agenda_items: [
    "Q2 roadmap review",
    "Feature prioritization",
    "Design sign-off",
    "Testing strategy",
  ],
  discussion_summary: [
    {
      topic: "Q2 Roadmap Review",
      summary:
        "The team reviewed the current Q2 roadmap and agreed that the mobile-first initiative should be the top priority given recent user feedback indicating 60% of users access the platform via mobile.",
      decisions: [
        "Mobile-first initiative elevated to P0 for Q2.",
        "Desktop feature freeze until mobile parity is achieved.",
      ],
    },
    {
      topic: "Feature Prioritization",
      summary:
        "Three features were debated: push notifications, offline mode, and advanced search. Push notifications won the vote given the highest estimated user impact.",
      decisions: [
        "Push notifications scoped for April release.",
        "Offline mode deferred to Q3.",
      ],
    },
    {
      topic: "Design Sign-Off",
      summary:
        "Priya presented revised wireframes. Minor adjustments to the onboarding flow were requested. Final designs due before sprint kick-off.",
      decisions: ["Revised wireframes approved pending minor onboarding edits."],
    },
    {
      topic: "Testing Strategy",
      summary:
        "Tom proposed a shift-left testing approach. The team agreed to integrate automated tests in the CI pipeline from day one of each sprint.",
      decisions: ["Automated tests to be added to CI pipeline immediately."],
    },
  ],
  action_items: [
    {
      action: "Update Q2 roadmap document with revised priorities",
      owner: "Sarah Johnson",
      due_date: "2024-04-12",
      status_remarks: "In progress",
    },
    {
      action: "Finalise mobile wireframes with onboarding adjustments",
      owner: "Priya Shah",
      due_date: "2024-04-14",
      status_remarks: "Pending",
    },
    {
      action: "Set up CI pipeline with automated test hooks",
      owner: "Tom Nguyen",
      due_date: "2024-04-17",
      status_remarks: "Pending",
    },
    {
      action: "Draft push notifications technical spec",
      owner: "Mark Lee",
      due_date: "2024-04-15",
      status_remarks: "Pending",
    },
  ],
  next_meeting: {
    date: "2024-04-24",
    time: "10:00 AM",
    agenda: "Sprint kick-off + design review",
  },
  additional_notes:
    "All participants to review the updated roadmap document prior to the next meeting. This is DEMO data generated by the fake AI provider.",
};

export class FakeAIProvider implements AIProvider {
  async extractMoM(): Promise<MoMData> {
    // Simulate network latency
    await new Promise((r) => setTimeout(r, 1200));
    return STUB;
  }
}
